import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window');

export const ProfileStyles = StyleSheet.create({
    mainContainer: {
    flex: 1,
    backgroundColor: '#FDFDFD',
  },
  headerSection: {
    alignItems: 'center',
  },
  topNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  avatarContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  avatarBorder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#F5F5F5',
    padding: 8,
  },
  avatarInner: {
    flex: 1,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#DDD',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  userName: {
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 12,
  },
  userRank: {
    fontSize: 14,
    color: '#888',
    marginTop: 2,
  },
  loyaltyCard: {
    width: width - 40,
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 25,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  loyaltyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loyaltyLabel: {
    fontSize: 14,
    color: '#666',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  pointsValue: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  giftCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFF9EF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressSection: {
    marginTop: 20,
  },
  progressBarBase: {
    height: 6,
    backgroundColor: '#FFF2D9',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#FFB039',
  },
  progressNote: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
    marginTop: 8,
    textAlign: 'center',
  },
  menuContainer: {
    paddingHorizontal: 20,
    marginTop: 25,
    paddingBottom: 40,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 40,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  leftContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  menuText: {
    fontSize: 16,
    color: '#1F1F1F',
    fontWeight: '500',
  },
  logoutBtn: {
    flexDirection: 'row',
    backgroundColor: '#FDEEE9',
    paddingVertical: 15,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    gap: 10,
  },
  logoutText: {
    color: '#E25822',
    fontWeight: 'bold',
    fontSize: 16,
  },
  versionText: {
    textAlign: 'center',
    color: '#BBB',
    fontSize: 12,
    marginTop: 25,
  },
  guestInfoBox: {},
  guestInfoText: {},
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: width * 0.85, backgroundColor: 'white', borderRadius: 24, padding: 24, alignItems: 'center', position: 'relative' },
  closeModalBtn: { position: 'absolute', right: 16, top: 16, zIndex: 10 },
  iconContainer: { width: 80, height: 80, backgroundColor: '#FFF2EE', borderRadius: 40, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 20, fontWeight: '700', color: '#1A1A1A', marginBottom: 8 },
  modalSubTitle: { fontSize: 15, color: '#666', textAlign: 'center', marginBottom: 20 },
  buttonGroup: { flexDirection: 'row', gap: 12 },
  cancelButton: { flex: 1, paddingVertical: 14, borderRadius: 16, backgroundColor: '#F5F5F5', alignItems: 'center' },
  cancelButtonText: { fontSize: 16, fontWeight: '600', color: '#666' },
  confirmButton: { width: '100%', paddingVertical: 14, borderRadius: 16, backgroundColor: '#E25822', alignItems: 'center' },
  confirmButtonText: { fontSize: 16, fontWeight: '600', color: 'white' },
  badgeLevel: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFB039', paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12, marginTop: 5 },
  badgeText: { color: '#FFF', fontSize: 12, fontWeight: 'bold', marginLeft: 4 },
  notifDot: { position: 'absolute', top: -2, right: -2, width: 12, height: 12, backgroundColor: '#E25822', borderRadius: 6, borderWidth: 2, borderColor: '#FFF' },
  rewardBox: { backgroundColor: '#FDF7F2', padding: 15, borderRadius: 12, width: '100%', marginBottom: 20, borderWidth: 1, borderColor: '#FFB039', borderStyle: 'dashed', alignItems: 'center' },
  rewardText: { color: '#E25822', fontWeight: 'bold', fontSize: 16, textAlign: 'center' },
  rewardSubText: { color: '#999', fontSize: 12, marginTop: 4 },
  codeBox: { backgroundColor: '#F4F4F4', padding: 20, borderRadius: 12, width: '100%', marginBottom: 20, alignItems: 'center', borderStyle: 'dashed', borderWidth: 1, borderColor: '#DDD' },
  codeLabel: { fontSize: 11, color: '#888', letterSpacing: 1, marginBottom: 5 },
  codeValue: { fontSize: 24, fontWeight: '800', color: '#1A1A1A', letterSpacing: 2 },
  rewardListSection: { marginTop: 20, paddingHorizontal: 20 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#333', marginBottom: 12 },
  horizontalScroll: { paddingRight: 20 },
  couponCardMini: { 
    width: 160, 
    height: 60, 
    backgroundColor: '#FFF', 
    borderRadius: 8, 
    marginRight: 12, 
    flexDirection: 'row', 
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFE0B2',
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 }
  },
  couponLeftMini: { width: 40, height: '100%', backgroundColor: '#FFF3E0', justifyContent: 'center', alignItems: 'center' },
  couponRightMini: { flex: 1, paddingHorizontal: 8 },
  couponValueMiniText: { fontSize: 13, fontWeight: '800', color: '#E25822' },
  couponCodeMiniText: { fontSize: 10, color: '#666', marginTop: 2, fontWeight: '600' },
  couponCircleTop: { position: 'absolute', top: -5, left: 35, width: 10, height: 10, borderRadius: 5, backgroundColor: '#FFF', zIndex: 1, borderWidth: 1, borderColor: '#FFE0B2' },
  couponCircleBottom: { position: 'absolute', bottom: -5, left: 35, width: 10, height: 10, borderRadius: 5, backgroundColor: '#FFF', zIndex: 1, borderWidth: 1, borderColor: '#FFE0B2' },
  modalOverlayBottom: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    height: '75%',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  modalTitleText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  modalSubTitleText: {
    fontSize: 12,
    color: '#888',
  },
  couponListContent: {
    paddingBottom: 30,
  },
  couponItemCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    marginBottom: 16,
    minHeight: 90,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    overflow: 'hidden',
  },
  couponLeftSection: {
    backgroundColor: '#E25822',
    width: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  couponStepContainer: {
    position: 'absolute',
    right: -5,
    height: '100%',
    justifyContent: 'space-around',
  },
  couponStepDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFF',
  },
  couponMiddleSection: {
    flex: 1,
    padding: 12,
    justifyContent: 'center',
  },
  couponValueText: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#333',
  },
  couponBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    backgroundColor: '#FFF3E0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  couponBadgeText: {
    color: '#E25822',
    fontSize: 11,
    fontWeight: 'bold',
  },
  couponExpiryText: {
    color: '#999',
    fontSize: 10,
    marginTop: 6,
  },
  couponCopyBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderLeftColor: '#DDD',
  },
  couponCopyText: {
    fontSize: 10,
    color: '#E25822',
    marginTop: 4,
    fontWeight: '500',
  },
  emptyStateContainer: {
    alignItems: 'center',
    marginTop: 50,
  },
  emptyStateText: {
    color: '#999',
    marginTop: 10,
    fontSize: 15,
  },
  // Thêm vào ProfileStyles.ts
ruleModalSheet: {
  backgroundColor: '#FFF',
  borderTopLeftRadius: 25,
  borderTopRightRadius: 25,
  maxHeight: '80%',
  padding: 20,
},
ruleHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 20,
},
ruleTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#333',
},
ruleItem: {
  flexDirection: 'row',
  marginBottom: 15,
  alignItems: 'flex-start',
},
ruleIcon: {
  width: 32,
  height: 32,
  borderRadius: 16,
  backgroundColor: '#FFF9F0',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
ruleTextContent: {
  flex: 1,
},
ruleItemTitle: {
  fontWeight: 'bold',
  fontSize: 14,
  color: '#444',
  marginBottom: 2,
},
ruleItemDesc: {
  fontSize: 13,
  color: '#777',
  lineHeight: 18,
},
ruleBadge: {
  backgroundColor: '#E25822',
  paddingHorizontal: 8,
  paddingVertical: 2,
  borderRadius: 10,
  marginTop: 5,
  alignSelf: 'flex-start'
}
})