import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window');
export const ProductDetailStyles = StyleSheet.create({
    container: {
        paddingTop: 15,
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 50,
        paddingBottom: 20,
    },
    headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#1A1A1A' },
    contentPadding: { paddingHorizontal: 20 },
    mainImage: {
        width: '100%',
        height: 280,
        borderRadius: 25,
        marginBottom: 20,
    },
    productName: { fontSize: 28, fontWeight: '900', color: '#1A1A1A' },
    priceRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 8 },
    price: { fontSize: 24, fontWeight: 'bold', color: '#F26522' },
    oldPrice: { fontSize: 18, color: '#999', textDecorationLine: 'line-through' },
    tagRow: { flexDirection: 'row', marginTop: 10 },
    tag: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 10,
    },
    brownTag: { backgroundColor: 'rgba(210, 160, 120, 0.4)' },
    whiteTag: { backgroundColor: '#FFFFFF' },
    tagText: { fontSize: 13, fontWeight: '600', marginLeft: 5, color: '#633D25' },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginTop: 25, marginBottom: 10 },
    description: { fontSize: 14, color: '#444', lineHeight: 22 },
    actionContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginTop: 30,
        justifyContent: 'space-between',
    },
    quantityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0F2F5',
        borderRadius: 25,
        paddingHorizontal: 15,
        width: width * 0.35,
        justifyContent: 'space-between',
    },
    quantityText: { fontSize: 18, fontWeight: 'bold' },
    addToCartButton: {
        flexDirection: 'row',
        backgroundColor: '#F26522',
        borderRadius: 25,
        paddingHorizontal: 25,
        paddingVertical: 15,
        width: width * 0.50,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 5,
        shadowColor: '#F26522',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    buyBtn: {
        flexDirection: 'row',
        backgroundColor: '#F26522',
        borderRadius: 25,
        paddingHorizontal: 25,
        paddingVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 5,
        shadowColor: '#F26522',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    addToCartText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
    nutritionCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        marginTop: 20,
        borderRadius: 20,
        padding: 15,
        justifyContent: 'space-around',
        elevation: 3,
    },
    nutritionItem: { alignItems: 'center' },
    nutritionLabel: { fontSize: 10, color: '#999', fontWeight: 'bold', marginBottom: 5 },
    nutritionValue: { fontSize: 18, fontWeight: 'bold', color: '#F26522' },
    mapContainer: {
        marginHorizontal: 20,
        marginTop: 30,
        height: 120,
        borderRadius: 20,
        overflow: 'hidden',
        position: 'relative',
    },
    mapImage: { width: '100%', height: '100%', opacity: 0.6, backgroundColor: '#CCC' },
    mapOverlay: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -50 }, { translateY: -15 }],
        backgroundColor: '#FFF',
        flexDirection: 'row',
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 20,
        alignItems: 'center',
    },
    mapText: { fontSize: 12, fontWeight: 'bold', marginLeft: 5, textTransform: 'uppercase' },

    storageCard: {
    backgroundColor: '#fff', 
    marginHorizontal: 20,
    marginTop: 20,
    padding: 15,
    borderRadius: 25,
    },
    storageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
    },
    storageTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#D16D2F',
    },
    storageContent: {
    flexDirection: 'column', 
    gap: 12,
    },
    storageItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    },
    storageItemText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    flex: 1,
    },
    nutritionWrapper: {
    backgroundColor: '#FFF',
    marginHorizontal: 20,
    marginTop: 20,
    padding: 15,
    borderRadius: 25,
    // Thêm shadow nếu cần
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    },
    nutritionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
    },

    // Thêm vào StyleSheet.create
    recipeCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 12,
    flexDirection: 'row',
    marginBottom: 15,
    alignItems: 'center',
    // Shadow cho iOS & Android
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    },
    recipeImage: {
    width: 100,
    height: 100,
    borderRadius: 15,
    backgroundColor: '#f0f0f0',
    },
    recipeInfo: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
    },
    recipeName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    },
    recipeMetaText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 4,
    },
    viewRecipeBtn: {
    backgroundColor: '#F26522', // Màu cam nút bấm
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
    marginTop: 10,
    alignSelf: 'flex-start',
    },
    viewRecipeBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    },
    emptyRecipeCard: {
    height: 120,
    borderWidth: 2,
    borderColor: '#A88E7A',
    borderStyle: 'dashed', // Nét đứt theo hình mẫu
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.6,
    },
    emptyRecipeText: {
    color: '#A88E7A',
    marginTop: 8,
    fontSize: 14,
    },

    usageSection: {
    marginTop: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 15,
    padding: 15,
    marginHorizontal: 15
  },
  usageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  usageContent: {
    paddingLeft: 5,
  },
  usageItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  usageBullet: {
    backgroundColor: '#D16D2F',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 2,
  },
  usageBulletText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  usageText: {
    flex: 1,
    fontSize: 14,
    color: '#4A2C2A',
    lineHeight: 20,
  },
})