import { StyleSheet } from "react-native";

export const TrackingStyles = StyleSheet.create({
    container: { 
    flex: 1, 
    backgroundColor: '#f5f5f5'
  },
  mapWrapper: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 100, 
  },
  etaCard: { 
    marginTop: 10,
    width: '100%', 
    backgroundColor: 'rgba(255, 255, 255, 0.95)', 
    borderRadius: 15, 
    padding: 15, 
    flexDirection: 'row', 
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
  },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#000' },
  header: { position: 'absolute', top: 50, flexDirection: 'row', alignItems: 'center', width: '100%', paddingHorizontal: 20, zIndex: 10 },
  headerTitle: { color: 'white', fontSize: 18, fontWeight: 'bold', flex: 1, textAlign: 'center' },
  etaIcon: { width: 45, height: 45, backgroundColor: 'rgba(76, 217, 100, 0.1)', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  etaLabel: { color: '#4cd964', fontSize: 10, fontWeight: 'bold' },
  etaTime: { color: '#4cd964', fontSize: 18, fontWeight: 'bold' },
  vLine: { width: 1, height: 30, backgroundColor: '#333', marginHorizontal: 15 },
  distText: { color: '#888', fontSize: 10 },
  dirValue: { color: '#4cd964', fontSize: 14, fontWeight: 'bold' },
  sheet: { position: 'absolute', bottom: -50, width: '100%', height: 420, backgroundColor: '#0a0a0a', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 20 },
  handle: { width: 40, height: 5, backgroundColor: '#333', alignSelf: 'center', borderRadius: 3, marginBottom: 25 },
  stepper: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 30, paddingHorizontal: 10 },
  stepCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#1a1a1a', justifyContent: 'center', alignItems: 'center' },
  stepActive: { backgroundColor: '#4cd964' },
  stepLabel: { fontSize: 8, color: '#555', marginTop: 5, fontWeight: 'bold', textAlign: 'center' },
  line: { height: 2, flex: 1, marginBottom: 15, marginHorizontal: -15 },
  lineActive: { backgroundColor: '#4cd964' },
  lineInactive: { backgroundColor: '#222' },
  userInfo: { flexDirection: 'row', alignItems: 'center', marginBottom: 35 },
  avatar: { width: 55, height: 55, borderRadius: 28, borderWidth: 2, borderColor: '#4cd964' },
  userName: { color: '#000', fontSize: 18, fontWeight: 'bold' },
  userAddr: { color: '#888', fontSize: 13, marginTop: 3 },
  userPhone: { color: '#000000', fontSize: 15, fontWeight: 600, marginTop: 3 },
  callCircle: { width: 45, height: 45, borderRadius: 23, backgroundColor: '#4cd964', justifyContent: 'center', alignItems: 'center' },
  slideContainer: { width: '100%', height: 70, backgroundColor: '#111', borderRadius: 35, justifyContent: 'center', padding: 5, borderWidth: 1, borderColor: '#1a331a' },
  slideThumb: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#4cd964', justifyContent: 'center', alignItems: 'center', zIndex: 10 },
  slideText: { position: 'absolute', width: '100%', textAlign: 'center', color: '#4cd964', fontWeight: 'bold', letterSpacing: 1 },
  shipperMarker: { backgroundColor: '#4cd964', padding: 6, borderRadius: 15, borderWidth: 2, borderColor: 'white' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  itemName: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
  },
  itemQty: {
    fontSize: 13,
    color: '#888',
    marginTop: 2,
  },
  itemPrice: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  modalFooter: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    paddingTop: 15,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  totalLabel: {
    fontSize: 16,
    color: '#666',
  },
  totalValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#E53935',
  },
  closeBtn: {
    backgroundColor: '#f5f5f5',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
})