import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window');
const itemWidth = (width - 45) / 2; 

export const RecipeStyle = StyleSheet.create({
    scrollContainer: {
    paddingTop: 15,
    paddingBottom: 20,
    paddingHorizontal: 15,
    backgroundColor: '#fff2e4', 
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1A1A1A',
  },
  viewAll: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#E25822',
    letterSpacing: 0.5,
  },
  featuredCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  featuredImage: {
    width: '100%',
    height: 200,
  },
  featuredBadge: {
    position: 'absolute',
    top: 15,
    left: 15,
    backgroundColor: '#E25822',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  featuredBadgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  featuredInfo: {
    padding: 15,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  featuredTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A1A1A',
  },
  featuredLevel: {
    fontSize: 14,
  },
  featuredDesc: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginBottom: 15,
  },
  metaInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaText: {
    fontSize: 13,
    color: '#333',
    marginLeft: 5,
    fontWeight: '500',
  },
  actionButton: {
    backgroundColor: '#E25822',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  actionButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },


  card: {
    width: itemWidth,
    marginBottom: 20,
  },
  imageWrapper: {
    width: '100%',
    height: 150,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  timeBadge: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  timeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#000',
  },
  title: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginTop: 10,
  },
  levelWrapper: {
    flexDirection: 'row',
    marginTop: 4,
  },
  levelIcon: {
    fontSize: 10,
    marginRight: 2,
  },

  // Detail
  recipeName: {textAlign: "center", fontWeight: 800, fontSize: 20, color: "#fff", paddingTop: 15, paddingBottom: 15, backgroundColor: "#e25822", borderRadius: 40},
  container: { flex: 1, backgroundColor: '#FFF' },
  videoContainer: { height: 250, backgroundColor: 'transparent', justifyContent: 'center', alignItems: 'center' },
  mainVideoImage: { width: '100%', height: '100%', opacity: 1 },
  playButton: { position: 'absolute', backgroundColor: 'rgba(0,0,0,0.5)', width: 70, height: 70, borderRadius: 35, justifyContent: 'center', alignItems: 'center' },
  videoControls: { position: 'absolute', bottom: 10, flexDirection: 'row', width: '90%', alignItems: 'center', justifyContent: 'space-between' },
  timeTextDetail: { color: 'white', fontSize: 12 },
  progressBarBg: { flex: 1, height: 3, backgroundColor: 'rgba(255,255,255,0.3)', marginHorizontal: 10, borderRadius: 2 },
  progressBarActive: { height: '100%', backgroundColor: '#E25822' },
  contentPadding: { padding: 20 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 15, borderWidth: 1, borderColor: '#F0F0F0', borderRadius: 20, marginBottom: 25 },
  summaryItem: { alignItems: 'center' },
  summaryValue: { fontSize: 18, textTransform: 'uppercase', fontWeight: 'bold', color: '#E25822' },
  summaryLabelRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  summaryLabel: { fontSize: 10, color: '#888', fontWeight: 'bold' },
  summaryDivider: { width: 1, height: '60%', backgroundColor: '#F0F0F0', alignSelf: 'center' },
  sectionHeaderDetail: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  sectionTitleDetail: { fontSize: 22, fontWeight: 'bold' },
  row: { flexDirection: 'row', alignItems: 'center' },
  addMoreText: { color: '#E25822', fontSize: 14, fontWeight: 'bold' },
  ingredientItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F9F9F9', padding: 15, borderRadius: 15, marginBottom: 10 },
  ingredientName: { fontSize: 15, marginLeft: 10, color: '#333' },
  ingredientWeight: { fontSize: 14, color: '#888' },
  stepContainer: { flexDirection: 'row', marginBottom: 5 },
  stepLeft: { alignItems: 'center', marginRight: 15 },
  stepNumber: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#E25822', justifyContent: 'center', alignItems: 'center', zIndex: 1 },
  stepNumberText: { color: 'white', fontWeight: 'bold' },
  stepLine: { width: 2, flex: 1, backgroundColor: '#F0F0F0', marginVertical: -5 },
  stepRight: { flex: 1, paddingBottom: 25 },
  stepTitle: { fontSize: 17, fontWeight: 'bold', marginBottom: 5 },
  stepDesc: { fontSize: 14, color: '#666', lineHeight: 20 },
  tipCard: { backgroundColor: '#FFF5F0', padding: 20, borderRadius: 20, marginTop: 10, marginBottom: 20 },
  tipTitle: { fontSize: 16, fontWeight: 'bold', color: '#E25822', paddingLeft: 8 },
  tipText: { fontSize: 14, color: '#555', lineHeight: 22, fontStyle: 'italic', marginTop: 10 },
  footer: { position: 'absolute', bottom: 0, width: '100%', flexDirection: 'row', padding: 15, paddingBottom: 30, paddingTop: 20, backgroundColor: 'white', borderTopWidth: 1, borderTopColor: '#F0F0F0', alignItems: 'center' },
  buyAllButton: { flex: 2, backgroundColor: '#E25822', height: 55, borderRadius: 28, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  buyAllText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
  favoriteButton: { flex: 1, alignItems: 'center' },
  favoriteText: { fontSize: 10, color: '#888', marginTop: 4, fontWeight: 'bold' },
})