import { StyleSheet } from "react-native";

export const CartStyles = StyleSheet.create({
  headerAction: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#fff',
  },
  badge: { 
    position: 'absolute', 
    top: -5, 
    left: -5, 
    backgroundColor: '#FF3B30', 
    paddingHorizontal: 6, 
    paddingVertical: 2, 
    borderRadius: 8, 
    borderWidth: 2, 
    borderColor: '#fff', 
  },
  textNone: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: 600,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  editBtn: {
    fontSize: 16,
    color: '#F26522',
    fontWeight: '600',
  },
  deleteBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 35,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  selectAll: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectAllText: {
    marginLeft: 8,
    fontSize: 16,
    color: '#333',
  },
  deleteBtn: {
    backgroundColor: '#FF3B30',
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 12,
  },
  deleteBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 12,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 15,
    backgroundColor: '#f5f5f5',
  },
  info: {
    flex: 1,
    marginLeft: 15,
  },
  name: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  oldPrice: {
    fontSize: 12,
    color: '#999',
    marginBottom: 2,
  },
  currentPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F26522',
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    padding: 4,
  },
  btnAction: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eee',
  },
  btnPlus: {
    backgroundColor: '#F26522',
    borderColor: '#F26522',
  },
  quantityText: {
    paddingHorizontal: 12,
    fontWeight: 'bold',
    fontSize: 14,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
})